// @ts-ignore Generated by the OpenNext build and absent before the first build.
import handler from './.open-next/worker.js'

const cronRoutes: Record<string, string> = {
  '0 5 * * *': '/api/cron/billing',
  '0 6 * * *': '/api/cron/check-tokens',
  '0 7 * * *': '/api/cron/sync-google-reviews',
}

type WorkerEnv = {
  APP_URL?: string
  CRON_SECRET?: string
  ENABLE_CRON_TRIGGERS?: string
}

type CronEvent = { cron: string }
type WorkerContext = { waitUntil(promise: Promise<unknown>): void }

export default {
  fetch: handler.fetch,
  async scheduled(event: CronEvent, env: WorkerEnv, ctx: WorkerContext) {
    if (env.ENABLE_CRON_TRIGGERS !== 'true') return
    const route = cronRoutes[event.cron]
    if (!route || !env.APP_URL || !env.CRON_SECRET) return

    // Dispatch internally: a same-zone fetch on a Worker route can reach the
    // legacy DNS origin instead of this Worker.
    ctx.waitUntil((async () => {
      const response = await handler.fetch(new Request(`${env.APP_URL}${route}`, {
        headers: { Authorization: `Bearer ${env.CRON_SECRET}` },
      }), env, ctx)
      await response.arrayBuffer()
      if (!response.ok) throw new Error(`Cron ${route} failed: HTTP ${response.status}`)
    })())
  },
}
