// Municipii și orașe din INS SIRUTA S1 2025 (CC BY 4.0).
// https://data.gov.ro/dataset/siruta-2025
export const ROMANIAN_CITIES = [
  " Adjud",
  " Codlea",
  " Gheorgheni",
  " Lupeni",
  " Marghita",
  " Moreni",
  " Toplița",
  " Vulcan",
  "Abrud",
  "Agnita",
  "Aiud",
  "Alba Iulia",
  "Alexandria",
  "Aleșd",
  "Amara",
  "Anina",
  "Aninoasa",
  "Arad",
  "Ardud",
  "Avrig",
  "Azuga",
  "Babadag",
  "Bacău",
  "Baia De Aramă",
  "Baia De Arieș",
  "Baia Mare",
  "Baia Sprie",
  "Balș",
  "Baraolt",
  "Bechet",
  "Beclean",
  "Beiuș",
  "Berbești",
  "Berești",
  "Bicaz",
  "Bistrița",
  "Blaj",
  "Bocșa",
  "Boldești-Scăeni",
  "Bolintin-Vale",
  "Borsec",
  "Borșa",
  "Botoșani",
  "Brad",
  "Bragadiru",
  "Brașov",
  "Breaza",
  "Brezoi",
  "Broșteni",
  "Brăila",
  "Bucecea",
  "București",
  "Budești",
  "Buftea",
  "Buhuși",
  "Bumbești-Jiu",
  "Buziaș",
  "Buzău",
  "Bușteni",
  "Bârlad",
  "Băbeni",
  "Băicoi",
  "Băile Govora",
  "Băile Herculane",
  "Băile Olănești",
  "Băile Tușnad",
  "Băilești",
  "Bălan",
  "Bălcești",
  "Cajvana",
  "Calafat",
  "Caracal",
  "Caransebeș",
  "Carei",
  "Cavnic",
  "Cehu Silvaniei",
  "Cernavodă",
  "Chitila",
  "Chișineu-Criș",
  "Ciacova",
  "Cisnădie",
  "Cluj-Napoca",
  "Comarnic",
  "Comănești",
  "Constanța",
  "Copșa Mică",
  "Corabia",
  "Costești",
  "Covasna",
  "Craiova",
  "Cristuru Secuiesc",
  "Cugir",
  "Curtea De Argeș",
  "Curtici",
  "Câmpeni",
  "Câmpia Turzii",
  "Câmpina",
  "Câmpulung",
  "Câmpulung Moldovenesc",
  "Călan",
  "Călimănești",
  "Călărași",
  "Căzănești",
  "Darabani",
  "Dej",
  "Deta",
  "Deva",
  "Dolhasca",
  "Dorohoi",
  "Dragomirești",
  "Drobeta-Turnu Severin",
  "Drăgănești-Olt",
  "Drăgășani",
  "Dumbrăveni",
  "Dăbuleni",
  "Dărmănești",
  "Eforie",
  "Fetești",
  "Fieni",
  "Fierbinți-Târg",
  "Filiași",
  "Flămânzi",
  "Focșani",
  "Frasin",
  "Fundulea",
  "Făget",
  "Făgăraș",
  "Fălticeni",
  "Făurei",
  "Galați",
  "Geoagiu",
  "Gherla",
  "Ghimbav",
  "Giurgiu",
  "Gura Humorului",
  "Găești",
  "Gătaia",
  "Hațeg",
  "Horezu",
  "Huedin",
  "Hunedoara",
  "Huși",
  "Hârlău",
  "Hârșova",
  "Ianca",
  "Iași",
  "Iernut",
  "Ineu",
  "Isaccea",
  "Jibou",
  "Jimbolia",
  "Lehliu-Gară",
  "Lipova",
  "Liteni",
  "Livada",
  "Luduș",
  "Lugoj",
  "Mangalia",
  "Medgidia",
  "Mediaș",
  "Miercurea Ciuc",
  "Miercurea Nirajului",
  "Miercurea Sibiului",
  "Mihăilești",
  "Milișăuți",
  "Mioveni",
  "Mizil",
  "Moinești",
  "Moldova Nouă",
  "Motru",
  "Murfatlar",
  "Murgeni",
  "Măcin",
  "Măgurele",
  "Mărășești",
  "Negrești",
  "Negrești-Oaș",
  "Negru Vodă",
  "Nehoiu",
  "Novaci",
  "Nucet",
  "Nădlac",
  "Năsăud",
  "Năvodari",
  "Ocna Mureș",
  "Ocna Sibiului",
  "Ocnele Mari",
  "Odobești",
  "Odorheiu Secuiesc",
  "Oltenița",
  "Onești",
  "Oradea",
  "Oravița",
  "Orăștie",
  "Orșova",
  "Otopeni",
  "Ovidiu",
  "Oțelu Roșu",
  "Panciu",
  "Pantelimon",
  "Pașcani",
  "Pecica",
  "Petrila",
  "Petroșani",
  "Piatra-Neamț",
  "Piatra-Olt",
  "Pitești",
  "Ploiești",
  "Plopeni",
  "Podu Iloaiei",
  "Pogoanele",
  "Popești-Leordeni",
  "Potcoava",
  "Predeal",
  "Pucioasa",
  "Pâncota",
  "Pătârlagele",
  "Recaș",
  "Reghin",
  "Reșița",
  "Roman",
  "Rovinari",
  "Roznov",
  "Roșiori De Vede",
  "Rupea",
  "Râmnicu Sărat",
  "Râmnicu Vâlcea",
  "Râșnov",
  "Răcari",
  "Rădăuți",
  "Salcea",
  "Salonta",
  "Satu Mare",
  "Scornicești",
  "Sebeș",
  "Sebiș",
  "Segarcea",
  "Seini",
  "Sfântu Gheorghe",
  "Sibiu",
  "Sighetu Marmației",
  "Sighișoara",
  "Simeria",
  "Sinaia",
  "Siret",
  "Slatina",
  "Slobozia",
  "Slănic",
  "Slănic-Moldova",
  "Solca",
  "Sovata",
  "Strehaia",
  "Suceava",
  "Sulina",
  "Sângeorgiu De Pădure",
  "Sângeorz-Băi",
  "Sânnicolau Mare",
  "Sântana",
  "Săcele",
  "Săcueni",
  "Săliște",
  "Săliștea De Sus",
  "Sărmașu",
  "Săveni",
  "Techirghiol",
  "Tecuci",
  "Teiuș",
  "Timișoara",
  "Tismana",
  "Titu",
  "Topoloveni",
  "Tulcea",
  "Turceni",
  "Turda",
  "Turnu Măgurele",
  "Târgoviște",
  "Târgu Bujor",
  "Târgu Cărbunești",
  "Târgu Frumos",
  "Târgu Jiu",
  "Târgu Lăpuș",
  "Târgu Mureș",
  "Târgu Neamț",
  "Târgu Ocna",
  "Târgu Secuiesc",
  "Târnăveni",
  "Tălmaciu",
  "Tăuții-Măgherăuș",
  "Tășnad",
  "Ulmeni",
  "Ungheni",
  "Uricani",
  "Urlați",
  "Urziceni",
  "Valea Lui Mihai",
  "Vaslui",
  "Vatra Dornei",
  "Vașcău",
  "Vicovu De Sus",
  "Victoria",
  "Videle",
  "Vișeu De Sus",
  "Vlăhița",
  "Voluntari",
  "Vânju Mare",
  "Vălenii De Munte",
  "Zalău",
  "Zimnicea",
  "Zlatna",
  "Zărnești",
  "Însurăței",
  "Întorsura Buzăului",
  "Șimleu Silvaniei",
  "Șomcuta Mare",
  "Ștefănești",
  "Ștei",
  "Țicleni",
  "Țăndărei"
] as const

export function normalizeCity(value: string): string {
  return value.trim().toLocaleLowerCase('ro-RO')
    .replace(/^(municipiul|orașul|oraşul|oraș|oraş)\s+/, '')
    .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
    .replace(/[șş]/g, 's').replace(/[țţ]/g, 't')
    .replace(/[^a-z0-9]/g, '')
}

const cityByNormalizedName = new Map<string, string>(
  ROMANIAN_CITIES.map((city) => [normalizeCity(city), city])
)

export function canonicalCity(value: string): string | null {
  return cityByNormalizedName.get(normalizeCity(value)) ?? null
}
