import type { Metadata } from 'next'
import Link from 'next/link'
import { LegalPage } from '@/components/ui/legal-page'
import { company } from '@/lib/company'

export const metadata: Metadata = { title: 'Termeni și condiții | BookEasy', description: 'Condițiile de utilizare a platformei SaaS BookEasy.' }

export default function TermsPage() {
  return (
    <LegalPage title="Termeni și condiții de utilizare" updatedAt="5 octombrie 2026" version="2.0" description="Contractul aplicabil utilizării platformei SaaS BookEasy de către afaceri și utilizatorii autorizați.">
      <div className="legal-callout"><strong>Important.</strong> Prin crearea unui cont, achiziționarea unui abonament sau continuarea utilizării BookEasy confirmi că ai citit și accepți acești termeni.</div>
      <nav className="legal-toc" aria-label="Cuprins"><strong>Cuprins</strong>{['Definiții','Obiectul contractului','Conturi și securitate','Nivelul serviciilor','Prețuri și plăți','Suspendare și încetare','Răspundere','Utilizare acceptabilă','Proprietate intelectuală','Modificări','Lege aplicabilă'].map((item, i) => <a key={item} href={`#cap-${i + 1}`}>{i + 1}. {item}</a>)}</nav>
      <h2 id="cap-1">1. Definiții</h2><p><strong>Platforma</strong> înseamnă serviciul software accesibil la bookeasy.ro, aplicația web progresivă, interfețele și funcțiile asociate. <strong>Furnizorul</strong> este {company.legalName}, CUI {company.cui}, {company.tradeRegistryNumber}, cu sediul în {company.registeredAddress}. <strong>Clientul</strong> este profesionistul sau persoana juridică ce contractează un abonament BookEasy. <strong>Utilizator final</strong> este persoana autorizată de Client să folosească Platforma.</p>
      <h2 id="cap-2">2. Obiectul contractului</h2><p>BookEasy oferă, în funcție de plan și configurare, administrarea programărilor, serviciilor, echipei, clienților, mesajelor, notificărilor, recenziilor, facturilor de abonament și integrărilor externe.</p><p>Furnizorul poate îmbunătăți, înlocui sau retrage funcții, cu informarea rezonabilă a Clientului atunci când schimbarea afectează material serviciul contractat.</p>
      <h2 id="cap-3">3. Conturi și securitate</h2><ul><li>Clientul furnizează informații corecte și actualizate și desemnează utilizatorii autorizați.</li><li>Credențialele sunt personale și nu vor fi divulgate.</li><li>Clientul răspunde pentru acțiunile efectuate din conturile sale și anunță imediat orice acces neautorizat.</li><li>Furnizorul poate limita temporar accesul pentru protejarea platformei sau investigarea unui incident.</li></ul>
      <h2 id="cap-4">4. Nivelul serviciilor</h2><p>Urmărim o disponibilitate lunară de 99,5%. Nu sunt incluse mentenanța planificată, incidentele furnizorilor terți, forța majoră, atacurile cibernetice de amploare ori problemele produse de configurația sau conexiunea Clientului. Această țintă nu reprezintă o garanție absolută de funcționare neîntreruptă.</p>
      <h2 id="cap-5">5. Prețuri, facturi și plăți</h2><ul><li>Tarifele și perioada de facturare sunt cele din oferta acceptată sau factura emisă individual Clientului.</li><li>Abonamentele se achită pe baza facturilor afișate în cont. Plata online, atunci când este activă, este procesată prin BT iPay; BookEasy nu stochează datele complete ale cardului.</li><li>Plata este considerată efectuată după confirmarea procesatorului sau înregistrarea încasării de către Furnizor.</li><li>Tarifele pot fi modificate cu notificare prealabilă de cel puțin 30 de zile pentru perioadele viitoare.</li></ul>
      <h2 id="cap-6">6. Suspendare și încetare</h2><p>Clientul poate solicita încetarea la {company.legalEmail}. Furnizorul poate suspenda contul pentru facturi neachitate, încălcări contractuale, risc de securitate sau obligații legale. Pentru facturile restante se aplică perioada de grație comunicată în cont sau pe factură.</p><p>După încetare, Clientul poate solicita exportul datelor într-un termen rezonabil. Datele sunt apoi șterse sau anonimizate, cu excepția celor ce trebuie păstrate conform legii, copiilor de siguranță aflate în ciclul normal de retenție și probelor necesare apărării unui drept.</p>
      <h2 id="cap-7">7. Răspundere</h2><p>BookEasy este un instrument tehnic. Afacerile răspund pentru serviciile oferite clienților lor, prețuri, reguli de anulare, informații profesionale și legalitatea datelor introduse. În limitele legii, Furnizorul nu răspunde pentru pierderi indirecte, profit nerealizat, acțiuni ale terților sau indisponibilitatea serviciilor externe.</p><p>Răspunderea totală a Furnizorului pentru prejudicii directe dovedite nu va depăși valoarea abonamentelor plătite în ultimele trei luni, cu excepția situațiilor în care legea interzice o asemenea limitare.</p>
      <h2 id="cap-8">8. Utilizare acceptabilă</h2><p>Este interzisă folosirea Platformei pentru activități ilegale, fraudă, spam, malware, acces neautorizat, colectare automată agresivă, eludarea controalelor de securitate, încălcarea drepturilor terților ori prelucrarea datelor fără un temei legal.</p>
      <h2 id="cap-9">9. Proprietate intelectuală</h2><p>Software-ul, marca, designul și documentația BookEasy aparțin Furnizorului sau licențiatorilor săi. Clientul primește un drept limitat, neexclusiv și netransferabil de utilizare pe durata abonamentului. Clientul rămâne titularul conținutului propriu și permite prelucrarea lui exclusiv pentru furnizarea serviciului.</p>
      <h2 id="cap-10">10. Modificarea termenilor</h2><p>Modificările importante vor fi comunicate, de regulă, cu cel puțin 15 zile înainte. Schimbările impuse de lege, securitate sau remedierea urgentă a unui risc pot intra în vigoare mai repede. Versiunea curentă este publicată pe această pagină.</p>
      <h2 id="cap-11">11. Lege aplicabilă și contact</h2><p>Contractul este guvernat de legea română și normele obligatorii ale Uniunii Europene. Părțile vor încerca soluționarea amiabilă înaintea sesizării instanțelor competente. Consumatorii pot sesiza <a href="https://anpc.ro/" target="_blank" rel="nofollow noopener noreferrer">ANPC</a> sau platforma <a href="https://ec.europa.eu/consumers/odr" target="_blank" rel="nofollow noopener noreferrer">SOL</a>.</p><p>Contact: <a href={`mailto:${company.legalEmail}`}>{company.legalEmail}</a>. Prelucrarea datelor este descrisă în <Link href="/legal/confidentialitate">Politica de confidențialitate</Link> și în <Link href="/dpa">DPA</Link>.</p>
    </LegalPage>
  )
}
